const data = {
  products: [
    {
      name: 'Choker 1',
      slug: 'choker-1',
      category: 'Chokers',
      image: '/images/choker1.jpg',
      price: 15,
      brand: 'Mariel Frias Original',
      rating: 4.99,
      numReviews: 8,
      countInStock: 14,
      description: 'Un choker muy bonito',
    },
    {
      name: 'Choker 2',
      slug: 'choker-2',
      category: 'Chokers',
      image: '/images/choker2.jpg',
      price: 15,
      brand: 'Mariel Frias Original',
      rating: 4.99,
      numReviews: 8,
      countInStock: 14,
      description: 'Otro choker muy bonito',
    },
    {
      name: 'Choker 3',
      slug: 'choker-3',
      category: 'Choker',
      image: '/images/choker3.jpg',
      price: 15,
      brand: 'Mariel Frias Original',
      rating: 4.99,
      numReviews: 8,
      countInStock: 14,
      description: 'Un ultimo choker muy bonito',
    },
    {
      name: 'Aretes 1',
      slug: 'aretes-1',
      category: 'Aretes',
      image: '/images/arete1.jpg',
      price: 15,
      brand: 'Mariel Frias Original',
      rating: 4.99,
      numReviews: 8,
      countInStock: 14,
      description: 'Un arete muy bonito',
    },
    {
      name: 'Aretes 2',
      slug: 'aretes-2',
      category: 'Aretes',
      image: '/images/arete2.jpg',
      price: 15,
      brand: 'Mariel Frias Original',
      rating: 4.99,
      numReviews: 8,
      countInStock: 14,
      description: 'Otro arete muy bonito',
    },
    {
      name: 'Aretes 3',
      slug: 'aretes-3',
      category: 'Aretes',
      image: '/images/arete3.jpg',
      price: 15,
      brand: 'Mariel Frias Original',
      rating: 4.99,
      numReviews: 8,
      countInStock: 14,
      description: 'Un ultimo arete muy bonito',
    },
  ],
};

export default data;
