import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-bold"> Buenas? </h1>
      <h2 classname="text-xl font-thin">Hola</h2>
      <h2 classname="text-xl font-thin">me</h2>
      <h2 classname="text-xl font-thin">llamo</h2>
      <h2 classname="text-xl font-thin">roberto</h2>
      <h2 classname="text-xl font-thin">hehe</h2>
    </div>
  );
}
